#!/bin/bash

sxhkd &

bspc config border_width 4
bspc config window_gap 5
bspc config bottom_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color "#d3a2d1"
bspc config active_border_color "#a7a2d3"
bspc config normal_border_color "#a7a2d3"
bspc config presel_feedback_color "#d3a2d1"


bspc config -m HDMI-0 bottom_padding 5
bspc config -m HDMI-0 right_padding 5
bspc config -m HDMI-0 left_padding 5
bspc config -m HDMI-0 top_padding 37

export DESKTOP_SESSION="gnome"

./.screenlayout/default.sh

bspc monitor HDMI-0 -n 1 -d 1 2 3 4 5 6
bspc monitor HDMI-1 -n 2 -d 7 8 9 10

mkdir /tmp/bspwm
udisksctl mount -b /dev/sda1

compton &
panel &
nm-applet &
nitrogen --restore
volumeicon &
sleep 0.5
bspc config -m 1 top_padding 37
bspc config -m 2 top_padding 0
stalonetray &
