#!/bin/bash

font_family='DejaVu Sans'
font_size=14

. panel_colors-dzen2

screen_width=1920
NORMIFS=$IFS
FIELDIFS=':'
PADDING='  '
MEGAPADDING='                '

while getopts 'f:s:' opt ; do
	case "$opt" in
		f)
			font_family=$OPTARG
			;;
		s)
			font_size=$OPTARG
			;;
	esac
done

shift $((OPTIND - 1))

while read -r line ; do
	case $line in
		E*)
			# emerge
			if ( echo $line | grep y >/dev/null )
			then
				line=$( echo $line | sed "s/y//" )
				emerge="^fg($COLOR_IND_ON)^bg($COLOR_STATUS_BG)${PADDING}${line#?}^fg()^bg()${MEGAPADDING}"
			else
				emerge="^fg($COLOR_STATUS_FG)^bg($COLOR_STATUS_BG)${PADDING}${line#?}^fg()^bg()${MEGAPADDING}"
			fi
			;;
		Z*)
			# battery
			battery="^fg($COLOR_BATTERY_FULL)^bg($COLOR_STATUS_BG)${line#?}^fg()^bg()"
			;;
		X*)
			# battery empty
			empty="^fg($COLOR_BATTERY_EMPTY)^bg($COLOR_STATUS_BG)${line#?}${PADDING}^fg()^bg()"
			;;
		Q*)
			# computer name
			compname="^fg($COLOR_STATUS_FG)^bg($COLOR_STATUS_BG)${line#?}${PADDING}^fg()^bg()"
			;;
		S*)
			# clock output
			sys_infos="^fg($COLOR_STATUS_FG)^bg($COLOR_STATUS_BG)${line#?}${PADDING}^fg()^bg()${PADDING}"
			;;
	esac
	printf "%s\n" "$emerge$battery$empty$sys_infos$compname"
done

