#! /bin/sh
. /usr/local/bin/profile

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config -m HDMI-0 top_padding 37
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf "T%s\n" > "$PANEL_FIFO" &
clock -sf 'S%a %I:%M %p' > "$PANEL_FIFO" &

. /usr/local/bin/panel_colors

/usr/local/bin/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g 3640x$PANEL_HEIGHT+100+5 -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" -u 3 -U "$COLOR_UNDERLINE" HDMI-0 | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
