#!/bin/bash

font_size=14
POW=''

. panel_colors-dzen2

screen_width=1920
NORMIFS=$IFS
FIELDIFS=':'
PADDING='  '
POW_SEP="^fg($COLOR_POWERLINE_BLOCK1)^bg($COLOR_POWERLINE_BLOCK3)$POW^fg($COLOR_POWERLINE_BLOCK3)^bg($COLOR_POWERLINE_BLOCK2)$POW"
POW_END="^fg($COLOR_POWERLINE_BLOCK2)^bg($COLOR_POWERLINE_BLOCK3)$POW^fg($COLOR_POWERLINE_BLOCK3)^bg($COLOR_BACKGROUND)$POW"

while getopts 'f:s:' opt ; do
	case "$opt" in
		f)
			font_family=$OPTARG
			;;
		s)
			font_size=$OPTARG
			;;
	esac
done

shift $((OPTIND - 1))

while read -r line ; do
	case $line in
        T*)
			# xtitle output
      if [ $(echo $line | wc -c) -gt 37 ];then
        line="$(echo $line | head -c 37)..."
      fi
      title="$POW_SEP^fg($COLOR_POWERLINE_TEXT2)^bg($COLOR_POWERLINE_BLOCK2)${PADDING}${line#?}${PADDING}^fg()^bg()$POW_END"
			;;

		W*)
			# bspwm internal state
			wm_infos=""
			IFS=$FIELDIFS
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				case $item in
					L*)
						# layout
						layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
						wm_infos="^fg($COLOR_POWERLINE_TEXT1)^bg($COLOR_POWERLINE_BLOCK1)${wm_infos}^ca(1, bspc desktop -l next)${PADDING}$layout${PADDING}^ca()"
						;;
				esac
				shift
			done
			IFS=$NORMIFS
			;;
	esac
	printf "%s\n" "$wm_infos$title"
done
