#!/bin/sh

desktop=$(bspc query -D -d focused)
tpad=$(cat /tmp/bspwm/tpad)
bpad=$(cat /tmp/bspwm/bpad)

for i in 1 2 3 4 5
do
    tpad=$(($tpad-2))
    bpad=$(($bpad-2))

    bspc config -d $desktop top_padding $tpad
    bspc config -d $desktop right_padding $tpad
    bspc config -d $desktop left_padding $tpad

    bspc config -d $desktop bottom_padding $tpad
done

echo $tpad > /tmp/bspwm/tpad
echo $bpad > /tmp/bspwm/bpad
